reference: http://www.objc.io/issue-6/travis-ci.html
language: objective-c
cache: bundler
script:
- xctool test -workspace Example/AKOFlipViewController.xcworkspace -scheme AKOFlipViewController -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
